# configuración del documento
title: Iniciativa de Datos Abiertos
desc: "Iniciativa de Datos Abiertos"
url: http://iniciativa-datos-abiertos.github.io/
repo_name: iniciativa-datos-abiertos.github.io
branch: master

# configuración global, no moverle
root_url: http://iniciativa-datos-abiertos.github.io
org_name: iniciativa-datos-abiertos
prose_url: http://prose.io

# configuración local, no es necesario editar
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown

