# configuración del documento
title: Iniciativa de Datos Abiertos
desc: "Política Nacional de Datos Abiertos"
url: http://localhost:4000
repo_name: datos-abiertos-mx.github.io
branch: master

# configuración global, no moverle
root_url: http://localhost:4000
org_name: datos-abiertos-mx
prose_url: http://prose.io

# configuración local, no es necesario editar
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown

